## Атрибуты

In [1]:
import numpy as np

In [9]:
# 1-мерный массив (вектор-строка)

arr_0 = np.random.randint(-10, 10, size=15)
arr_0

array([-4, -5, -9,  3,  8,  8, -2, -7,  3,  9,  6,  7, -6,  3,  5])

In [13]:
# 2-мерный массив (матрица)

arr_1 = np.random.rand(3,5)
arr_1

array([[0.92410868, 0.05561329, 0.82190122, 0.02327978, 0.70178547],
       [0.02620598, 0.02236406, 0.31647136, 0.09327209, 0.5720543 ],
       [0.71198447, 0.15392795, 0.75432491, 0.70799735, 0.88145783]])

In [14]:
# форма

arr_0.shape

(15,)

In [15]:
arr_1.shape

(3, 5)

In [16]:
# тип данных массивов
arr_0.dtype

dtype('int32')

In [17]:
arr_1.dtype

dtype('float64')

In [18]:
# мерность массива (количество измерений, осей)
arr_1.ndim

2

In [19]:
# занимаемый объем памяти (в байтах)
arr_1.nbytes

120

In [21]:
# количесвто элементов массива
arr_1.size

15

## Методы массивов

In [23]:
arr_1

array([[0.92410868, 0.05561329, 0.82190122, 0.02327978, 0.70178547],
       [0.02620598, 0.02236406, 0.31647136, 0.09327209, 0.5720543 ],
       [0.71198447, 0.15392795, 0.75432491, 0.70799735, 0.88145783]])

In [24]:
arr_1.dtype

dtype('float64')

In [26]:
# конвертация типа данных
arr_2 = arr_1.astype("float16")
arr_2

array([[0.9243 , 0.0556 , 0.822  , 0.02328, 0.7017 ],
       [0.0262 , 0.02237, 0.3164 , 0.09326, 0.5723 ],
       [0.712  , 0.1539 , 0.7544 , 0.708  , 0.8813 ]], dtype=float16)

In [28]:
# транспонирование - поворот матрицы по диагонали (с верхнего левого на правый)
# arr_2.transpose()
arr_2.T

array([[0.9243 , 0.0262 , 0.712  ],
       [0.0556 , 0.02237, 0.1539 ],
       [0.822  , 0.3164 , 0.7544 ],
       [0.02328, 0.09326, 0.708  ],
       [0.7017 , 0.5723 , 0.8813 ]], dtype=float16)

In [32]:
arr_2

array([[0.9243 , 0.0556 , 0.822  , 0.02328, 0.7017 ],
       [0.0262 , 0.02237, 0.3164 , 0.09326, 0.5723 ],
       [0.712  , 0.1539 , 0.7544 , 0.708  , 0.8813 ]], dtype=float16)

In [30]:
# минимальное максимальное и средне-арифметическое значения

arr_2.min(axis=0), arr_2.max(axis=1), arr_2.mean()

(array([0.0262 , 0.02237, 0.3164 , 0.02328, 0.5723 ], dtype=float16),
 array([0.9243, 0.5723, 0.8813], dtype=float16),
 0.4512)

In [33]:
# индексы минимального и маскимального значений
arr_2.argmin(), arr_2.argmax()

(6, 0)

In [34]:
arr_2.argmin(axis=0), arr_2.argmax(axis=1)

(array([1, 1, 1, 0, 1], dtype=int64), array([0, 4, 4], dtype=int64))

In [35]:
arr_0

array([-4, -5, -9,  3,  8,  8, -2, -7,  3,  9,  6,  7, -6,  3,  5])

In [36]:
# метод сортировки значений массива (от меньшего к большему)
arr_0.sort()

In [37]:
arr_0

array([-9, -7, -6, -5, -4, -2,  3,  3,  3,  5,  6,  7,  8,  8,  9])

In [38]:
# переворот отсортированного массива от большего к меньшему
arr_0[::-1]

array([ 9,  8,  8,  7,  6,  5,  3,  3,  3, -2, -4, -5, -6, -7, -9])

In [39]:
arr_3 = np.random.randint(10, size=15)
arr_3

array([4, 5, 5, 3, 9, 6, 1, 0, 3, 5, 3, 7, 4, 7, 5])

In [40]:
# метод возвращающий индексы сортированных значений
arr_3.argsort()

array([ 7,  6,  3,  8, 10,  0, 12,  1,  2,  9, 14,  5, 11, 13,  4],
      dtype=int64)

In [41]:
# сортировка двумерного массива (самостоятельно)

## Индексация

In [43]:
np.random.seed(0)
arr_4 = np.random.randint(-10, 10, size=(3,4))
arr_4

array([[  2,   5, -10,  -7],
       [ -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2]])

In [44]:
# прямая индексация
arr_4[1]

array([-7, -3, -1,  9])

In [45]:
# обратная индексация
arr_4[-1]

array([ 8, -6, -4,  2])

In [46]:
# извлечение знаения элементов массива
# стандартный питоновский синтаксис
arr_4[-1][2]

-4

In [47]:
# numpy-евский синтаксис
arr_4[-1, 2]

-4

In [48]:
# запись значения
arr_4[-1, 2] = 100
arr_4

array([[  2,   5, -10,  -7],
       [ -7,  -3,  -1,   9],
       [  8,  -6, 100,   2]])

##  Срезы


In [49]:
arr_4

array([[  2,   5, -10,  -7],
       [ -7,  -3,  -1,   9],
       [  8,  -6, 100,   2]])

In [50]:
# срез строк
arr_4[1:]

array([[ -7,  -3,  -1,   9],
       [  8,  -6, 100,   2]])

In [53]:
# срез столбцов
arr_4[:,:3]

array([[  2,   5, -10],
       [ -7,  -3,  -1],
       [  8,  -6, 100]])

In [54]:
# срез по строкам и столбцам
arr_4[1:,:3]

array([[ -7,  -3,  -1],
       [  8,  -6, 100]])

In [55]:
arr_4

array([[  2,   5, -10,  -7],
       [ -7,  -3,  -1,   9],
       [  8,  -6, 100,   2]])

In [56]:
# Срез создает не новый независимый массив, 
# а создает представление исходного (view), поэтому при последующих изменениях, меняется исходник

arr_5 = arr_4[1:,:3]
arr_5

array([[ -7,  -3,  -1],
       [  8,  -6, 100]])

In [57]:
arr_5[-1, -1] = 9235
arr_5

array([[  -7,   -3,   -1],
       [   8,   -6, 9235]])

In [58]:
arr_4

array([[   2,    5,  -10,   -7],
       [  -7,   -3,   -1,    9],
       [   8,   -6, 9235,    2]])

In [67]:
# копия массива - возвращает независимый массив
arr_6 = arr_4[1:,:3].copy()
arr_6

array([[777, 777, 777],
       [777, 777, 777]])

In [68]:
arr_6[-1, -1] = 121
arr_6

array([[777, 777, 777],
       [777, 777, 121]])