## Операции

In [2]:
import numpy as np

In [5]:
# 1-мерные массивы
arr_0 = np.arange(1, 11)
arr_0

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr_1 = np.arange(0, 19, 2)
arr_1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# Поэлементное сложение
# решение с применением стандартного питонячего инструментария 
def arr_sum(a, b):
    res = []
    for idx, val in enumerate(a):
        res.append(val + b[idx])
    return np.array(res)
        

In [9]:
%timeit arr_sum(arr_0, arr_1)

15.2 µs ± 2.08 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
# решение с применением NumPy
%timeit arr_0 + arr_1

1.85 µs ± 375 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
%timeit np.add(arr_0, arr_1)

2.05 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
arr_0 + arr_1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [16]:
# поэлементное умножение 2-мерных массивов
arr_2 = np.arange(9)
arr_3 = arr_2.reshape((3,3))
arr_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr_4 = np.arange(1,10).reshape((3,3))
arr_4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr_3 * arr_4

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [20]:
# Точечное умножение
# скалярное произведение
r_vector = np.arange(3)
c_vector = np.arange(3).reshape((3,1))

r_vector, c_vector

(array([0, 1, 2]),
 array([[0],
        [1],
        [2]]))

In [21]:
np.dot(r_vector, c_vector)

array([5])

In [22]:
r_vector @ c_vector

array([5])

In [23]:
# Точечное умножение вектора на матрицу
matrix = np.arange(3*2).reshape((3,2))
matrix

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
r_vector @ matrix

array([10, 13])

In [25]:
# точечное умножение матрицы на матрицу (матричное умножение)
matrix_1 = np.arange(2*2).reshape((2,2))
matrix_2 = np.arange(2*2).reshape((2,2)).T

matrix_1, matrix_2

(array([[0, 1],
        [2, 3]]),
 array([[0, 2],
        [1, 3]]))

In [26]:
matrix_1 @ matrix_2

array([[ 1,  3],
       [ 3, 13]])

In [28]:
# логические операции
arr_3, arr_4

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [29]:
# поэлементное сравнение
arr_3 != arr_4

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [30]:
# сравнение массива со скаляром
arr_3 < 5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [31]:
# все ли значения массива больше 5?
np.all(arr_3 > 5)

False

In [32]:
# есть ли хоть одно значение в массиве которое больше 5?
np.any(arr_3>5)

True

In [34]:
# маскирование

np.random.seed(0)

arr_5 = np.random.randint(10, size=5)
arr_5

array([5, 0, 3, 3, 7])

In [35]:
mask = arr_5 >= 5
mask

array([ True, False, False, False,  True])

In [36]:
arr_5[mask]

array([5, 7])

In [37]:
arr_6 = np.random.randint(10, size=7)
arr_6

array([9, 3, 5, 2, 4, 7, 6])

In [38]:
arr_6[arr_6 >= 5]

array([9, 5, 7, 6])